### PR TITLE
Ported FSM to Typescript + bugfixes + a minor interface change

### PR DESCRIPTION
**Pull request by evenius**
Yep, you guessed it, it's ya hungry boi Jonathan. 🕺🏻

⚠️Notice!!⚠️

This will not be mergeable before [this `@adludio/erx` pull request](https://github.com/FutureAdLabs/erx/pull/4)  is merged. It depends on types from there.

That's why CircleCI is complaining :/

Here is the gist of this PR:

👨🏽‍🎨 Updated in the style of @adludio/erx and @adludio/geometry

🌊 Now on build generates typescript + flow-definitions for usefulness in other projects

🐛 Caught a bug where it sets `this.transitioning` to `true` when entering a state, but it only sets it to false if there's an actual onEnter-function, meaning that in some cases it will be stuck in `this.transitioning`

👷‍♂️ Added error thrown when it tries to `goTo()` non-existant state -> This should never happen in prod, and it should protect against misspellings (`FSM Error: Tried to reach non-existant state: "wiin-statte"`).

♻️ Changed States to have default {} to instead letting triggers having a default {}. It makes sense to have an FSM where you manually traverse all the states with goto, but to me it seems nonsenical to enforce non-empty triggers on an empty state machine?

💞 Changed order of arguments in constructor, just to make sure that any optional variable always comes last. 

Previously:
```
new FSM(triggers, state)
```

Now:

```
new FSM(state, triggers)
```

⏱ Added ability to read last state (m.lastState) machine was in. The reason for this is that there's a case where it makes a different if you come to win from "blue-screen" or "green-screen". It's good for debugging too :)

### Fixed all types except for a like two, will hit up #dev-admaker to go over these questions on monday

`HooksFn -> Return what? Typed How?`

### CODE REVIEW

**Comment by evenius** [comment]
Oh shit, also fixes all security-issues 😎

**Review by HDykins — APPROVED** [review]
Nice! Looks like you've moved it to TS and fixed that transitioning bug. I don't really understand why you've switched the position of states and triggers args, I suppose it doesn't make a massive difference, just thought it would be familiar for dev builders is triggers was first.

**Comment by evenius** [comment]
Alright, so the answer to why, is because it's like convention for Javascript that things with defaultVariables is last. So it can be called like


```typescript
new FSM(states)
```

```typescript
new FSM(undefined, states)
```

**Comment by evenius** [comment]
Aaand I didn't think it made sense to have triggers for states that (without any states), but I can see a time where we'd have states without triggers (for example if you want to _only_ use m.goto to traverse the states)

**Pull request merged**
